# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
include: https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml

variables:
  BUNDLE: deja-dup-dev.flatpak

# Disabled until https://github.com/fsfe/reuse-tool/issues/223 is fixed
# reuse_lint:
#   image: fsfe/reuse
#   script:
#     - rm -f repo.tar  # gitlab adds repo.tar file
#     - reuse lint

vala_lint:
  image: valalang/lint
  script: io.elementary.vala-lint -c vala-lint.conf .

flatpak:
  extends: .flatpak
  variables:
    MANIFEST_PATH: flatpak/org.gnome.DejaDupDevel.yaml
    MESON_ARGS: -Dprofile=Devel
    FLATPAK_MODULE: deja-dup
    RUNTIME_REPO: https://nightly.gnome.org/gnome-nightly.flatpakrepo
    APP_ID: org.gnome.DejaDupDevel

nightly:
  extends: .publish_nightly
  dependencies:
    - flatpak
