# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
include: https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml

reuse_lint:
  image:
    name: fsfe/reuse
    entrypoint: [""]
  script: reuse lint

vala_lint:
  image: valalang/lint
  script: io.elementary.vala-lint -c vala-lint.conf .

flatpak:
  extends: .flatpak
  variables:
    APP_ID: org.gnome.DejaDupDevel
    BUNDLE: org.gnome.DejaDupDevel.flatpak
    FLATPAK_MODULE: deja-dup
    MANIFEST_PATH: flatpak/org.gnome.DejaDupDevel.yaml
    RUNTIME_REPO: https://nightly.gnome.org/gnome-nightly.flatpakrepo

nightly:
  extends: .publish_nightly
  dependencies:
    - flatpak
