#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry

set -e

pos=$(ls */ -1d | cut -d/ -f1 | grep -v '^C$')

test -e LINGUAS
echo "$pos" | diff -u -B -I '^#.*' LINGUAS -
