#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2 -*-

# Dogtail requires this
gsettings set org.gnome.desktop.interface toolkit-accessibility true

EXISTING=$(ps x -o pid,cmd | grep deja-dup | sed 's/^ *\([0-9]\+\).*/\1/')
if [ -n "$EXISTING" ]; then
  kill -9 $EXISTING 2>/dev/null
fi

export DEJA_DUP_TEST_FAST_FAIL=1

if [ "$1" = "--snap" ]; then
  shift
  export XDG_DATA_DIRS=$HOME/snap/deja-dup/current/.local/share:$XDG_DATA_DIRS
  export DD_MONITOR_EXEC=deja-dup.monitor
  export DD_CACHE_DIR=$HOME/snap/deja-dup/common/.cache/deja-dup
  export DD_APPID=org.gnome.DejaDup

elif [ "$1" = "--dev" ]; then
  shift

  BUILDDIR=$(realpath ./builddir)
  mkdir -p "${BUILDDIR}/tmpshare/glib-2.0/schemas"
  cp "${BUILDDIR}/data/org.gnome.DejaDupDevel.gschema.xml" "${BUILDDIR}/tmpshare/glib-2.0/schemas"
  glib-compile-schemas "${BUILDDIR}/tmpshare/glib-2.0/schemas"

  export XDG_DATA_DIRS="${BUILDDIR}/tmpshare:${XDG_DATA_DIRS}"
  export PATH="${BUILDDIR}/deja-dup:${PATH}"
  export DD_MONITOR_EXEC="${BUILDDIR}/deja-dup/monitor/deja-dup-monitor"
  export DD_CACHE_DIR=$HOME/.cache/deja-dup
  export DD_APPID=org.gnome.DejaDupDevel

  if grep '^ID.*debian$' /etc/os-release >/dev/null; then
    export DD_DEBIAN_DUPLICITY=1
  fi

else
  echo "Must provide a mode"
  exit 1
fi

exec pytest-3 $*
