#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry

set -e

# Emulate pkexec's clearing of environment, but keep test ones
VARS="DEJA_DUP_TEST_AS_ROOT=1 $(env | grep ^DEJA_DUP_ | tr '\n' ' ')"
VARS="$VARS PATH=$PATH XDG_DATA_DIRS=$XDG_DATA_DIRS XDG_CACHE_HOME=$XDG_CACHE_HOME"

# Test that first argument is our custom duplicity polkit script
echo $1 | grep '.*/deja-dup/duplicity'
shift

env -i $VARS "$(dirname $0)/../../tools/duplicity/duplicity" $*
