#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry

set -e

test -d .git || exit 0

sources=$(git ls-files | grep -e '\.vala$' -e '^data/ui/' -e '^data/.*\.in$' | grep -v '/tests/')

test -e po/POTFILES.in
echo "$sources" | diff -u -B -I '^#.*' po/POTFILES.in -
