#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry

set -e

test -d ../.git || exit 0

pos=$(git ls-files | grep '\.po$' | cut -d. -f1)

test -e LINGUAS
echo "$pos" | diff -u -B -I '^#.*' LINGUAS -
