# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
---
name: deja-dup
version: git
version-script: grep 'version:' meson.build -m1 | cut -d\' -f2
summary: Déjà Dup Backup Tool
description: |
  An easy to use personal backup system for your GNOME desktop.

  https://wiki.gnome.org/Apps/DejaDup
icon: data/icons/org.gnome.DejaDup.svg
license: GPL-3.0+

grade: stable
confinement: classic

base: core18

apps:
  deja-dup:
    command: bin/wrapper
    desktop: share/applications/org.gnome.DejaDup.desktop
    environment:
      PATH: $SNAP/bin:$PATH
      PYTHONPATH: $SNAP/lib/python2.7/site-packages
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
  monitor:
    command: bin/monitor.wrapper
    environment:
      PATH: /snap/bin:$PATH
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    passthrough:
      autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./snap/local

  duplicity:
    plugin: python
    python-version: python2
    source: https://launchpad.net/duplicity/0.7-series/0.7.18.2/+download/duplicity-0.7.18.2.tar.gz
    source-type: tar
    build-packages:
      - librsync-dev
    stage-packages:
      - librsync1
      - python-boto
      - python-cloudfiles
      - python-gi
      - python-swiftclient

  deja-dup:
    plugin: meson
    source: .
    source-type: git
    meson-parameters:
      - --prefix=/snap/deja-dup/current
    organize:
      snap/deja-dup/current: .
    build-packages:
      - appstream-util
      - desktop-file-utils
      - itstool
      - libglib2.0-bin
      - libglib2.0-dev
      - libgoa-1.0-dev
      - libgoa-backend-1.0-dev
      - libgpg-error-dev
      - libgtk-3-dev
      - libsecret-1-dev
      - valac
    stage-packages:
      - libgoa-1.0-0b
      - libgoa-backend-1.0-1
      - libgtk-3-0
      - libsecret-1-0
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' share/applications/org.gnome.DejaDup.desktop
      glib-compile-schemas share/glib-2.0/schemas
