# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
---
name: deja-dup
version: git
version-script: grep 'version:' meson.build -m1 | cut -d\' -f2
summary: Déjà Dup Backup Tool
description: |
  An easy to use personal backup system for your GNOME desktop.

  https://wiki.gnome.org/Apps/DejaDup
icon: data/icons/org.gnome.DejaDup.svg
license: GPL-3.0+

grade: stable
confinement: classic

base: core18

apps:
  deja-dup:
    command: desktop-launch $SNAP/bin/wrapper
    desktop: share/applications/org.gnome.DejaDup.desktop
    common-id: org.gnome.DejaDup
    environment:
      PATH: $SNAP/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.6/site-packages:$SNAP/usr/lib/python3/dist-packages
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      GIO_MODULE_DIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
      GTK_EXE_PREFIX: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  monitor:
    command: desktop-launch $SNAP/bin/monitor.wrapper
    autostart: org.gnome.DejaDup.Monitor.desktop
    environment:
      PATH: $SNAP/bin:$PATH
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      GIO_MODULE_DIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
      GTK_EXE_PREFIX: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  duplicity:
    command: bin/duplicity
    environment:
      PYTHONPATH: $SNAP/lib/python3.6/site-packages:$SNAP/usr/lib/python3/dist-packages
      GIO_MODULE_DIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules

parts:
  dump:
    plugin: dump
    source: ./snap/local

  duplicity:
    after:
      - dump
    plugin: python
    python-version: python3
    source: https://launchpad.net/duplicity/0.8-series/0.8.05/+download/duplicity-0.8.05.tar.gz
    source-type: tar
    python-packages:
      - cffi==1.11.5  # gets pulled in by pyrax, and we need to lock to same version as Ubuntu ships
      - pyrax  # not packaged in Ubuntu
      - PyDrive  # not packaged in Ubuntu
    build-packages:
      - ieee-data  # python-netaddr links to this, but does not depend on it
      - libffi-dev
      - librsync-dev
    stage-packages:
      - librsync1
      - python3-boto
      - python3-gi
      - python3-swiftclient
    override-prime: |
      snapcraftctl prime
      patch -p0 < python3.patch
      rm python3.patch

  deja-dup:
    plugin: meson
    source: .
    source-type: git
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current
    organize:
      snap/deja-dup/current: .
    build-packages:
      - appstream-util
      - dbus
      - desktop-file-utils
      - gettext
      - itstool
      - libglib2.0-bin
      - libglib2.0-dev
      - libgoa-1.0-dev
      - libgpg-error-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - valac
    stage-packages:
      - gvfs-backends
      - libgoa-1.0-0b
      - libgtk-3-0
      - libjson-glib-1.0-0
      - libsecret-1-0
      - libsoup2.4-1
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' share/applications/org.gnome.DejaDup.desktop
      glib-compile-schemas share/glib-2.0/schemas


  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
      - FLAVOR=gtk3
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
